GRANT CREATE TABLE TO GHOREYSHI;
GRANT CREATE ANY TABLE TO GHOREYSHI;
GRANT CREATE PROCEDURE TO GHOREYSHI;
GRANT CREATE ANY PROCEDURE TO GHOREYSHI;
GRANT EXECUTE ANY PROCEDURE TO GHOREYSHI;
GRANT CREATE SESSION TO GHOREYSHI;
GRANT SELECT ANY TABLE TO GHOREYSHI;