CREATE USER GHOREYSHI PROFILE DEFAULT IDENTIFIED BY "oracle"
DEFAULT TABLESPACE TBS_GHOREYSHI_DWH
TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT SELECT ANY DICTIONARY TO GHOREYSHI;
GRANT UNLIMITED TABLESPACE TO GHOREYSHI;
GRANT CONNECT TO GHOREYSHI;
GRANT RESOURCE TO GHOREYSHI;